/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crayne_sketch_util_lib_NativeSketchLibrary */

#ifndef _Included_org_crayne_sketch_util_lib_NativeSketchLibrary
#define _Included_org_crayne_sketch_util_lib_NativeSketchLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crayne_sketch_util_lib_NativeSketchLibrary
 * Method:    terminalWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_crayne_sketch_util_lib_NativeSketchLibrary_terminalWidth
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_sketch_util_lib_NativeSketchLibrary
 * Method:    terminalHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_crayne_sketch_util_lib_NativeSketchLibrary_terminalHeight
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_sketch_util_lib_NativeSketchLibrary
 * Method:    keyPress
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_crayne_sketch_util_lib_NativeSketchLibrary_keyPress
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_sketch_util_lib_NativeSketchLibrary
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_crayne_sketch_util_lib_NativeSketchLibrary_init
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_sketch_util_lib_NativeSketchLibrary
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_crayne_sketch_util_lib_NativeSketchLibrary_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
