/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crayne_jtux_util_lib_NativeJTuxLibrary */

#ifndef _Included_org_crayne_jtux_util_lib_NativeJTuxLibrary
#define _Included_org_crayne_jtux_util_lib_NativeJTuxLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crayne_jtux_util_lib_NativeJTuxLibrary
 * Method:    terminalWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_crayne_jtux_util_lib_NativeJTuxLibrary_terminalWidth
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_jtux_util_lib_NativeJTuxLibrary
 * Method:    terminalHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_crayne_jtux_util_lib_NativeJTuxLibrary_terminalHeight
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_jtux_util_lib_NativeJTuxLibrary
 * Method:    keyPress
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_crayne_jtux_util_lib_NativeJTuxLibrary_keyPress
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_jtux_util_lib_NativeJTuxLibrary
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_crayne_jtux_util_lib_NativeJTuxLibrary_init
  (JNIEnv *, jclass);

/*
 * Class:     org_crayne_jtux_util_lib_NativeJTuxLibrary
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_crayne_jtux_util_lib_NativeJTuxLibrary_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
